extends RefCounted
class_name InkboundLocalization

const LANGUAGE_AUTO := "auto"
const LANGUAGE_ENGLISH := "en"
const LANGUAGE_CHINESE := "zh_CN"
const LANGUAGE_CHOICES := [LANGUAGE_AUTO, LANGUAGE_ENGLISH, LANGUAGE_CHINESE]

# English source text remains the canonical content and save-data representation.
# The runtime translation is registered before any UI is constructed so Godot's
# built-in Control translation and explicit dynamic-string translation agree.
const ZH_CN := {
	# Language and common UI.
	"LANGUAGE": "语言",
	"SYSTEM": "跟随系统",
	"ENGLISH": "English",
	"SIMPLIFIED CHINESE": "简体中文",
	"ON": "开",
	"OFF": "关",
	"FULL": "强",
	"HALF": "中",
	"GENTLE": "柔和",
	"FULLSCREEN": "全屏",
	"WINDOWED": "窗口",
	"OPEN": "打开",
	"BACK": "返回",
	"CLOSE": "关闭",
	"PREVIOUS": "上一页",
	"NEXT": "下一页",
	"CONTINUE": "继续",
	"REVEAL": "显示全文",
	"CHOICE": "选择",
	"COMMON": "普通",
	"RARE": "稀有",
	"EPIC": "史诗",
	"LEGENDARY": "传说",
	"CURRENT DRAFT": "当前构筑",
	"DRAFT": "草稿",
	"CHAPTER": "章节",
	"TECHNIQUE": "技巧",
	"Choose a stroke to continue.": "选择一笔以继续。",
	"RELIC": "遗物",
	"Choose a memory to bind into this draft.": "选择一段记忆装订进本局草稿。",
	"RUN RELIC": "本局遗物",
	"RESONANT": "共鸣",
	"AWAKENS": "即将觉醒",
	"BUILD AWAKENED": "构筑觉醒",
	"MASTERWORK": "构筑大成",
	"LOCKED": "未解锁",
	"COMPLETE": "已完成",
	"NEW": "新",
	"PAUSED": "已暂停",
	"OPTIONS": "选项",
	"MANUAL": "手册",
	"CODEX": "图鉴",
	"ACHIEVEMENTS": "成就",
	"HISTORY": "记录",
	"OPTIONS & ACCESSIBILITY": "选项与辅助功能",
	"MASTER VOLUME": "主音量",
	"MUSIC VOLUME": "音乐音量",
	"SFX VOLUME": "音效音量",
	"GAMEPAD VIBRATION": "手柄振动",
	"CONTROLLER AIM ASSIST": "手柄瞄准辅助",
	"SCREEN SHAKE": "画面震动",
	"IMPACT FREEZE": "打击停顿",
	"REDUCED FLASHES": "减弱闪烁",
	"DISPLAY MODE": "显示模式",
	"CONTROL BINDINGS": "按键绑定",
	"D-PAD / ARROWS SELECT   LEFT/RIGHT ADJUST": "方向键选择   左/右调整",
	"B/○  ·  START/ESC  BACK": "B/○  ·  START/ESC  返回",
	"ACTION                         KEYBOARD / MOUSE                         GAMEPAD": "动作                         键盘 / 鼠标                         手柄",
	"A/ENTER REBIND  ·  Y RESET DEFAULTS  ·  B/ESC BACK": "A/回车 重新绑定  ·  Y 恢复默认  ·  B/ESC 返回",
	"MOVE UP": "向上移动",
	"MOVE DOWN": "向下移动",
	"MOVE LEFT": "向左移动",
	"MOVE RIGHT": "向右移动",
	"SLASH": "斩击",
	"DASH": "冲刺",
	"INK ART": "墨术",
	"PAUSE": "暂停",
	"ART": "墨术",
	"COOLDOWN": "冷却",
	"INK": "墨迹",
	"ELITES": "精英",
	"HOLD": "坚守",
	"ENTER": "进入",
	"MASKS": "面具",
	"REWARD": "奖励",
	"ORDER FULFILLED": "指令已完成",
	"AOE": "范围",
	"+HP": "回血",
	"MAKE THE FINAL MARK": "落下最后一笔",
	"FIELD NOTES": "战地手记",
	"THE FIRST CUT": "第一刀",
	"READ THE PAGE": "读懂战场",
	"WRITE A BUILD": "构筑流派",
	"RESTORE AND RETURN": "修复与归来",
	"CREDITS & LEGAL": "制作名单与法律信息",
	"SURVIVE TWELVE TIMED PAGES.\n\nWhite and gold shapes warn attacks; cyan diamonds are hostile shots; crimson ground is danger. Dash during impact to pass through harm. Defeated masks drop Ink, recovery, Memory, and rare combat supplies. Pages 4, 8, and 12 end with an authored boss encounter.": "在十二个限时页章中存活。\n\n白色与金色图形表示攻击预警，青色菱形是敌方子弹，绯红地面代表危险。命中瞬间冲刺可穿过伤害。击败面具会掉落墨迹、恢复品、记忆与稀有战斗补给。第 4、8、12 页将迎来首领战。",
	"INK RAISES YOUR LEVEL AND PAUSES THE PAGE.\n\nChoose techniques to write one of six disciplines. At 3 and 6 matching points it awakens a run bonus. Once a discipline has 2 points, every draft includes one RESONANT choice for it. Relics last this draft. Weapon forms replace slash rhythm and Ink Art.": "收集墨迹可升级，并在选择技巧时暂停战场。\n\n技巧会书写六种流派之一；同类达到 3 点与 6 点时会觉醒本局加成。任一流派达到 2 点后，每次升级都保证出现一个对应的“共鸣”选项。遗物持续整局；武器形态会改变斩击节奏与墨术。",
	"EVERY DRAFT RECOVERS A DIFFERENT MARGIN.\n\nRoutes and Directives change each attempt. Daily Chronicle (T / D-pad down) fixes one dated seed and seals Restoration for comparable drafts. After an ending, P / left-stick click opens the Proof Ledger. Banked Memory buys ranks with M / right-stick click. Save & Return preserves a live draft; Story Archive replays scenes safely.": "每一局草稿都会修复不同的页边。\n\n路线与页章指令每局变化。每日编年史（T / 十字键下）使用固定日期种子，并封印修复加成以便公平比较。完成结局后，按 P / 左摇杆打开校样账簿。按 M / 右摇杆用已存记忆购买等级。“保存并返回”会保留当前进度；故事档案可安全重播剧情。",
	"DESIGN, NARRATIVE, CODE, AND PRODUCTION\nManga Forge project pipeline\n\nENGINE\nGodot Engine - Juan Linietsky, Ariel Manzur, and contributors - MIT License\n\nART & AUDIO\nOriginal project assets; selected narrative illustrations created with OpenAI image tools under project direction. Full notices ship beside the executable in THIRD_PARTY_NOTICES.txt.": "设计、叙事、代码与制作\nManga Forge 项目流水线\n\n引擎\nGodot Engine - Juan Linietsky、Ariel Manzur 及贡献者 - MIT 许可证\n\n美术与音频\n项目原创资产；部分叙事插画在项目指导下使用 OpenAI 图像工具创作。完整声明随可执行文件一同提供，见 THIRD_PARTY_NOTICES.txt。",
	"WASD / ARROWS   MOVE\nMOUSE   AIM\nLEFT MOUSE / J   SLASH\nRIGHT MOUSE / SPACE / K   DASH\nMIDDLE MOUSE / E   INK ART\nESC   PAUSE        F1 / H   MANUAL": "WASD / 方向键   移动\n鼠标   瞄准\n鼠标左键 / J   斩击\n鼠标右键 / 空格 / K   冲刺\n鼠标中键 / E   墨术\nESC   暂停        F1 / H   手册",
	"LEFT STICK / D-PAD   MOVE\nRIGHT STICK   AIM\nX / RIGHT TRIGGER   SLASH\nA / LEFT BUMPER   DASH\nB   INK ART\nSTART   PAUSE        LEFT TRIGGER   MANUAL": "左摇杆 / 十字键   移动\n右摇杆   瞄准\nX / 右扳机   斩击\nA / 左肩键   冲刺\nB   墨术\nSTART   暂停        左扳机   手册",

	# Story archive and character names.
	"PROLOGUE": "序章",
	"THE BLANK PAGE": "空白之页",
	"ACT I COMPLETE": "第一幕 完",
	"WHAT THE MASK HID": "面具之下",
	"ACT II COMPLETE": "第二幕 完",
	"THE FORBIDDEN BINDERY": "禁忌装订所",
	"ACT III": "第三幕",
	"THE FIRST AUTHOR": "初代作者",
	"FINAL REVISION": "最终修订",
	"WHO OWNS A MEMORY?": "记忆属于谁？",
	"ENDING: MARGINS": "结局：页边",
	"NOTHING ERASED": "不再抹除",
	"ENDING: LOOSE LEAVES": "结局：散页",
	"A WORLD UNBOUND": "无缚之世",
	"NARA": "奈良",
	"IORI": "伊织",
	"MORROW": "莫罗",
	"MORROW, THE MARGINALIA": "莫罗，页边之刃",
	"THE RED EDITOR": "赤红编辑",
	"THE BINDER": "装订者",
	"NARRATOR": "旁白",
	"Nara... if they take my name, keep the shape of it.": "奈良……若他们夺走我的名字，请替我记住它的形状。",
	"I woke beneath the Grand Archive with a blade in my hand and my sister's voice trapped inside it.": "我在大档案馆下方醒来，手里握着一把刀，姐姐的声音被困在刀中。",
	"The Editors have cut every forbidden memory from the city. Their scraps learned to wear masks.": "编辑者从城中剪去了所有禁忌记忆。那些碎片学会了戴上面具。",
	"Then I will cut a road through the redactions. No page stays blank while I still remember.": "那我就从删改中劈出一条路。只要我还记得，就不会让任何一页继续空白。",
	"You call them monsters because we spared you their faces.": "你称他们为怪物，因为我们仁慈地抹去了他们的脸。",
	"The broken mask held a memory: a baker, laughing with flour on his hands.": "破碎的面具里藏着一段记忆：一个面包师，双手沾满面粉，笑得很开心。",
	"Every enemy here was once a life the Archive decided was inconvenient.": "这里的每个敌人，都曾是被档案馆判定为“不合时宜”的生命。",
	"I am not hunting pages anymore. I am bringing people home.": "我不再追猎书页。我要带他们回家。",
	"A city survives by forgetting. I merely choose the memories that cost too much.": "城市靠遗忘存续。我只是替它挑出代价太高的记忆。",
	"Nara... the masks are dreaming through me. I remember all of them.": "奈良……面具正借我做梦。我记得他们每一个人。",
	"You erased Iori because she found the first draft of our world.": "你们抹去伊织，是因为她找到了这个世界的初稿。",
	"Ask your sword who wrote that draft.": "问问你的刀，那份初稿是谁写的。",
	"I did. Before I became your blade, they called me the First Author.": "是我。在成为你的刀之前，他们称我为初代作者。",
	"The thing ahead is the ending I tore away: my hunger to make a flawless world.": "前方之物，是我亲手撕掉的结局——那个渴望创造无瑕世界的自己。",
	"Perfection is only a page where nobody was allowed to leave a mark.": "所谓完美，不过是一页不准任何人留下笔迹的纸。",
	"Give me the blade, Nara. One clean revision, and no one will ever suffer again.": "把刀给我，奈良。只需一次干净的修订，就再也不会有人受苦。",
	"A painless lie is still an erasure. I choose the messy truth.": "没有痛苦的谎言仍是抹除。我选择杂乱的真相。",
	"The blank page can restore every stolen memory—or dissolve the Archive forever.": "空白之页能恢复所有被盗的记忆——也能让档案馆永远消解。",
	"There is no perfect ending. There is only the cost you choose to remember.": "没有完美的结局，只有你选择铭记的代价。",
	"Then let the final mark be mine.": "那就让我落下最后一笔。",
	"PRESERVE THE SCARS": "保留伤痕",
	"Return the memories and rebuild the Archive.": "归还记忆，重建档案馆。",
	"BREAK THE BINDING": "斩断装订",
	"Free every memory, even if the old world ends.": "释放所有记忆，即使旧世界因此终结。",
	"We restored the memories with every stain intact. The city grieved, argued, forgave—and became real again.": "我们恢复了记忆，也保留了每一处污痕。城市悲恸、争吵、宽恕——终于再次真实。",
	"The Archive no longer decides what is worthy. Anyone may write in its margins.": "档案馆不再裁定何者值得留存。任何人都能在页边写下自己的话。",
	"I became an ordinary sword. It was the kindest ending an author could receive.": "我成了一把普通的刀。这是一个作者所能得到的最温柔结局。",
	"There are still masks beyond the final shelf. Tomorrow, we bring them home too.": "最后一排书架之外仍有面具。明天，我们也带他们回家。",
	"I broke the binding. The Archive fell upward in a storm of names, recipes, crimes, lullabies, and unfinished goodbyes.": "我斩断了装订。档案馆在姓名、菜谱、罪行、摇篮曲与未尽告别的风暴中向天空坠落。",
	"Without an official history, we had to meet one another and ask what happened.": "没有官方历史，我们只好彼此相见，亲口询问曾经发生的一切。",
	"The world became harder to control—and impossible to erase.": "世界变得更难掌控——也再无法被抹除。",
	"We carried no map into the next draft. For once, that felt like freedom.": "我们没带地图走进下一份草稿。第一次，那感觉像是自由。",

	# Techniques and relics.
	"RAZOR INK": "锋刃墨",
	"+0.75 blade damage": "+0.75 斩击伤害",
	"WIDE PANEL": "宽幅分镜",
	"Longer, wider slash arc": "斩击弧更长、更宽",
	"RAPID STROKE": "疾速笔触",
	"Attack 14% faster": "攻击速度提高 14%",
	"RED THREAD": "赤线",
	"+9% critical chance": "+9% 暴击率",
	"GHOST STEP": "幽灵步",
	"Faster movement and dash": "移动与冲刺更快",
	"IRON GUTTER": "铁页沟",
	"+2 max health and heal": "+2 最大生命并恢复生命",
	"OVERFLOW": "漫墨",
	"More cleave and knockback": "提高横扫范围与击退",
	"LAMINATED SOUL": "覆膜之魂",
	"Gain 7% damage reduction": "获得 7% 伤害减免",
	"MARGIN MAGNET": "页边磁石",
	"Pull pickups from farther away": "从更远处吸取掉落物",
	"SCHOLAR'S LUCK": "学者之运",
	"Better relic and recovery drops": "提高遗物与恢复品掉率",
	"LIVING FOOTNOTE": "活体脚注",
	"Regenerate slowly after avoiding damage": "一段时间未受伤后缓慢恢复",
	"BLOOD ANNOTATION": "血色批注",
	"Heal from every twelfth kill": "每击败十二名敌人恢复生命",
	"INK WAVE": "墨刃波",
	"Every fourth slash fires a cutting wave": "每第四次斩击发射一道墨刃波",
	"RETURNING STROKE": "回锋",
	"Ink waves return and strike twice": "墨刃波返回并造成第二次命中",
	"SPLINTER SCRIPT": "裂字",
	"Ink waves split after a hit": "墨刃波命中后分裂",
	"BLEEDING LETTERS": "泣血字迹",
	"Slashes stack damaging bleed": "斩击叠加流血伤害",
	"EMBER MARGIN": "余烬页边",
	"Critical hits burn nearby masks": "暴击灼烧附近面具",
	"COLD READING": "冷读",
	"Hits slow enemies; frozen foes shatter": "命中使敌人减速；冻结敌人会碎裂",
	"EXECUTION CLAUSE": "处决条款",
	"Execute badly wounded non-boss enemies": "处决重伤的非首领敌人",
	"CRITICAL ECHO": "暴击回响",
	"Critical hits repeat at half damage": "暴击以一半伤害重复一次",
	"DASHING PERIOD": "冲刺句点",
	"Dash ends with a damaging ink burst": "冲刺结束时释放伤害墨爆",
	"AFTERIMAGE CUT": "残影斩",
	"Your dash trail damages pursuers": "冲刺残迹伤害追击者",
	"PERFECT MARGIN": "无瑕页边",
	"Untouched streaks build damage": "连续无伤会逐步提高伤害",
	"CRESCENDO": "渐强",
	"Repeated hits accelerate your blade": "连续命中会加快刀速",
	"GREATBRUSH FORM": "巨笔形态",
	"Heavy, enormous strokes with brutal knockback": "沉重巨幅的笔触，带来猛烈击退",
	"NEEDLEPOINT FORM": "针锋形态",
	"Fast narrow cuts with extreme critical focus": "高速窄幅斩击，极度专注暴击",
	"SEAL-CASTER FORM": "印契使形态",
	"Trade reach for relentless ink waves": "牺牲近战范围，持续发射墨刃波",
	"TWIN-STROKE FORM": "双锋形态",
	"Each attack follows with a mirrored cut": "每次攻击追加一道镜像斩击",
	"THE LAST WORD": "最终话",
	"At one health, damage and dash recovery surge": "生命降至 1 时，伤害与冲刺恢复大幅提高",
	"OPEN BOOK": "开卷",
	"+1 upgrade choice and better rarity": "+1 升级选项并提高稀有度",
	"LIVING INK": "活墨",
	"Ink Arts deal 25% more damage": "墨术伤害提高 25%",
	"QUICKSCRIPT": "速写",
	"Ink Arts recover 14% faster": "墨术冷却加快 14%",
	"VIOLENT MARGIN": "狂暴页边",
	"Ink Arts cover a wider area": "墨术覆盖范围更大",
	"RED HARVEST": "赤红收割",
	"Blade hits recharge your Ink Art": "斩击命中可恢复墨术冷却",
	"ECHOED PANEL": "回响分镜",
	"Ink Arts repeat at 45% power": "墨术以 45% 威力重复一次",
	"MERCIFUL REVISION": "仁慈修订",
	"An Ink Art hitting five masks heals 1": "一次墨术命中五个面具时恢复 1 生命",
	"BROKEN MASK": "破碎面具",
	"+15% damage against elites and bosses": "对精英与首领伤害 +15%",
	"IORI'S RIBBON": "伊织的缎带",
	"The first lethal hit each run leaves you at 1 health": "每局首次受到致命伤时保留 1 生命",
	"RED PENCIL": "赤红铅笔",
	"Every tenth hit is guaranteed critical": "每第十次命中必定暴击",
	"FORBIDDEN LIBRARY CARD": "禁书馆借阅证",
	"+20% Ink and shard value": "墨迹与记忆碎片价值 +20%",
	"GLASS NIB": "玻璃笔尖",
	"+35% critical damage, -10% max health": "+35% 暴击伤害，-10% 最大生命",
	"BROKEN BINDER CHAIN": "断裂装订链",
	"Nearby enemies are slowed after a dash": "冲刺后使附近敌人减速",
	"MORROW'S BLACK TEA": "莫罗的红茶",
	"Heal at the start of every new page": "每个新页章开始时恢复生命",
	"ROYAL WAX SEAL": "王家蜡封",
	"Ink waves grow larger and pierce once": "墨刃波变大并额外穿透一次",
	"LUCKY MISPRINT": "幸运错印",
	"Small chance for defeated enemies to drop twice": "击败敌人时小概率获得双倍掉落",
	"PAPER HEART": "纸心",
	"+4 max health; recovery can overheal into guard": "+4 最大生命；过量恢复转化为护盾",
	"EMPTY FRAME": "空画框",
	"Standing still briefly grants a damage aura": "短暂站立不动可获得伤害光环",
	"THE FIRST DRAFT": "初稿",
	"+0.5 damage and +5% critical chance": "+0.5 伤害，+5% 暴击率",
	"+0.5 damage and +5% critical chance.": "+0.5 伤害，+5% 暴击率。",

	# Weapons, routes and hazards.
	"MARGINALIA BLADE": "页边之刃",
	"MARGINALIA": "页边之刃",
	"INK EDGE": "墨锋",
	"RED LOGIC": "赤红逻辑",
	"GHOST DRAFT": "幽灵草稿",
	"LIVING SCRIPT": "活体墨文",
	"BOUND PAGE": "坚装之页",
	"+8 reach and +1 cleave": "+8 攻击距离与 +1 横扫目标",
	"+0.5 blade damage, +2 reach, +1 cleave": "+0.5 斩击伤害、+2 攻击距离、+1 横扫目标",
	"+5% critical chance": "+5% 暴击率",
	"+30% critical damage": "+30% 暴击伤害",
	"Attack 6% faster": "攻击速度提高 6%",
	"+8 movement and +1 combo power": "+8 移速与 +1 连段强度",
	"Dash recovers 10% faster": "冲刺恢复加快 10%",
	"Dash gains a nova and cutting afterimage": "冲刺获得墨爆与伤害残影",
	"Ink Arts recover 10% faster": "墨术恢复加快 10%",
	"Slashes gain ink waves; Ink Art deals +15%": "斩击获得墨刃波；墨术伤害 +15%",
	"+1 max health and heal": "+1 最大生命并恢复生命",
	"Gain recovery, reduction, and 2 Ward": "获得恢复、减伤与 2 点护盾",
	"PALIMPSEST RING": "复写之环",
	"Balanced and flexible; restored transformations remain in the technique pool.": "均衡灵活；已修复的武器形态仍会出现在技巧池中。",
	"GREATBRUSH": "巨笔",
	"FINAL PERIOD": "终焉句点",
	"Slow enormous strokes and brutal knockback; locks other forms.": "缓慢的巨幅笔触与强力击退；锁定其他形态。",
	"NEEDLEPOINT": "针锋",
	"RED LINE": "赤线",
	"Rapid narrow critical cuts; locks other forms.": "快速窄幅暴击斩击；锁定其他形态。",
	"SEAL-CASTER": "印契使",
	"SEAL STORM": "印契风暴",
	"Short reach and a wave on every slash; locks other forms.": "近战范围较短，每次斩击发射墨刃波；锁定其他形态。",
	"TWIN-STROKE": "双锋",
	"CROSS REVISION": "交叉修订",
	"Measured attacks followed by mirrored cuts; locks other forms.": "稳健攻击追加镜像斩击；锁定其他形态。",
	"WHISPER STACKS": "低语书栈",
	"WHISPER": "低语",
	"Soft shelves answer with borrowed voices.": "柔软书架用借来的声音回应。",
	"ENTER ECHO SANCTUARIES\nRANGED MASKS · MORE HEALS\nSCORE ×1.08": "进入回声圣域\n远程面具 · 更多恢复\n得分 ×1.08",
	"Echo sanctuaries slow masks and restore Ink Art · ×1.08 score": "回声圣域使面具减速并恢复墨术 · 得分 ×1.08",
	"ECHO SANCTUARY": "回声圣域",
	"Enter the speaking circle when it resolves.": "圆环成形时进入低语区域。",
	"RAZOR GALLERY": "锋刃画廊",
	"RAZOR": "锋刃",
	"Portrait frames close like sharpened teeth.": "肖像画框如锋利牙齿般合拢。",
	"DODGE RAZOR SWEEPS\nCHARGERS · TOUGHER MASKS\nSCORE ×1.12": "躲避锋刃横扫\n冲锋者 · 更坚韧的面具\n得分 ×1.12",
	"Telegraphed razor lines cut both sides · ×1.12 score": "预警锋线从两侧切入 · 得分 ×1.12",
	"RAZOR SWEEP": "锋刃横扫",
	"Cross the red line before the frame closes.": "画框闭合前越过红线。",
	"BLACK INDEX": "黑色索引",
	"INDEX": "索引",
	"Forbidden names bleed through every card.": "禁忌姓名从每张卡片中渗血。",
	"EVADE REDACTION STAMPS\nMORE ELITES · FEWER HEALS\nMEMORY ×1.24": "躲避删改印章\n更多精英 · 更少恢复\n记忆 ×1.24",
	"Redaction stamps erase crowded ground · ×1.15 score": "删改印章抹除拥挤区域 · 得分 ×1.15",
	"REDACTION STAMP": "删改印章",
	"Leave the marked card before it turns black.": "标记卡片变黑前离开。",
	"CHAIN VAULT": "锁链秘库",
	"CHAIN": "锁链",
	"Contradictory histories strain against iron thread.": "相互矛盾的历史在铁线中挣扎。",
	"CROSS ROTATING CHAINS\nCENSORS · SPLITTERS\nARMORED · SCORE ×1.14": "穿越旋转锁链\n审查者 · 分裂者\n重甲 · 得分 ×1.14",
	"Crossing chain lines bind player and masks · ×1.14 score": "交叉锁链束缚玩家与面具 · 得分 ×1.14",
	"BINDING CROSS": "装订十字",
	"Move between the two tightening chain lines.": "在两道收紧的锁链之间移动。",
	"ERRATA CANALS": "勘误运河",
	"ERRATA": "勘误",
	"Loose sentences hunt through rivers of wet ink.": "游离语句在湿墨河流中狩猎。",
	"ESCAPE INK SURGES\nTELEPORTERS · LEECHES\nFASTER · SCORE ×1.15": "逃离墨潮\n传送者 · 吸血者\n更快 · 得分 ×1.15",
	"Canal surges sweep a telegraphed lane · ×1.15 score": "运河墨潮扫过预警区域 · 得分 ×1.15",
	"ERRATA SURGE": "勘误墨潮",
	"Leave the flashing ink lane or ride its current.": "离开闪烁墨道，或顺流而行。",
	"CONTRABAND HALL": "违禁品大厅",
	"MARKET": "市集",
	"Stolen memories change hands beneath red lanterns.": "被盗记忆在红灯笼下易手。",
	"CLAIM VOLATILE CACHES\nMORE ELITE TRADERS\nMEMORY ×1.32": "夺取不稳定秘藏\n更多精英商贩\n记忆 ×1.32",
	"Claim timed contraband before its lantern burns · ×1.16 score": "灯笼燃尽前夺取限时违禁品 · 得分 ×1.16",
	"VOLATILE CACHE": "不稳定秘藏",
	"Touch the cache for Memory and Ward before it explodes.": "秘藏爆炸前触碰它，获得记忆与护盾。",
	"WHITE ROOM": "纯白之室",
	"WHITE": "纯白",
	"An unwritten chamber tries to erase every wound.": "未被书写的房间试图抹去一切伤口。",
	"SHARE REVISION FIELDS\nWARDENS · HEALERS\nDURABLE · SCORE ×1.14": "争夺修订力场\n守卫 · 治疗者\n耐久 · 得分 ×1.14",
	"White fields heal every body inside them · ×1.14 score": "白色力场治疗其中所有单位 · 得分 ×1.14",
	"WHITE REVISION": "纯白修订",
	"Take the healing field only after clearing its masks.": "清除面具后再占据治疗力场。",
	"RED PRESS": "赤红印刷机",
	"PRESS": "印刷机",
	"The first printing machine stamps verdicts in blood.": "第一台印刷机用鲜血盖下判决。",
	"DODGE TRIPLE VERDICTS\nDUELISTS · WARDENS\nDEADLIER · SCORE ×1.18": "躲避三重判决\n决斗者 · 守卫\n更致命 · 得分 ×1.18",
	"The Red Press stamps three lethal verdicts · ×1.18 score": "赤红印刷机盖下三道致命判决 · 得分 ×1.18",
	"TRIPLE VERDICT": "三重判决",
	"Read all three circles before the press falls.": "印刷机落下前看清三处圆形预警。",
	"LOOSE LEAVES": "散页",
	"LEAVES": "散页",
	"Unbound pages become a storm with no center.": "未装订的书页化作没有中心的风暴。",
	"READ THE PAGE GUSTS\nLARGER RAPID HORDES\nLIGHTER · SCORE ×1.20": "观察书页阵风\n更大更快的敌群\n更轻 · 得分 ×1.20",
	"Page gusts reposition the entire battle · ×1.20 score": "书页阵风推动整片战场 · 得分 ×1.20",
	"PAGE GUST": "书页阵风",
	"Use the arrows to prepare for the coming push.": "根据箭头方向准备应对推力。",

	# Enemies, achievements and progression.
	"Forgotten Mask": "遗忘面具",
	"Red Comma": "赤红逗号",
	"Heavy Redaction": "重型删改者",
	"Margin Scribe": "页边抄写员",
	"Torn Paragraph": "撕裂段落",
	"Name Thief": "窃名者",
	"Gutter Warden": "页沟守卫",
	"Iron Censor": "铁甲审查者",
	"Errata Shade": "勘误暗影",
	"False Archivist": "伪档案员",
	"Living Inkblot": "活体墨团",
	"Margin Duelist": "页边决斗者",
	"The Red Editor": "赤红编辑",
	"The Binder": "装订者",
	"The First Author": "初代作者",
	"pursuer": "追击者",
	"telegraphed charger": "预警冲锋者",
	"slow tank": "缓慢重甲",
	"ranged skirmisher": "远程游击者",
	"splits on death": "死亡时分裂",
	"fast life-drainer": "高速吸血者",
	"area denial": "区域封锁",
	"frontal shield; flank or break": "正面持盾；绕后或破盾",
	"teleports behind the player": "传送至玩家身后",
	"heals and hastes nearby masks": "治疗并加速附近面具",
	"stationary radial hazard": "固定环形威胁",
	"timed parry and counter-rush": "定时格挡与反冲锋",
	"act one boss": "第一幕首领",
	"act two boss": "第二幕首领",
	"final boss": "最终首领",
	"First Cut": "第一刀",
	"Defeat your first mask.": "击败第一个面具。",
	"Hundred Redactions": "百次删改",
	"Defeat 100 enemies across all drafts.": "在所有草稿中累计击败 100 名敌人。",
	"Thousand Cuts": "千刀",
	"Defeat 1,000 enemies across all drafts.": "在所有草稿中累计击败 1,000 名敌人。",
	"Page Turner": "翻页者",
	"Reach Page 4.": "抵达第 4 页。",
	"Last Page": "最终页",
	"Reach Page 12.": "抵达第 12 页。",
	"One True Ending?": "唯一真结局？",
	"Complete either ending.": "完成任一结局。",
	"Both Margins": "页边两侧",
	"Complete both endings.": "完成两个结局。",
	"Contract Bound": "契约缠身",
	"Clear any contract.": "完成任意契约。",
	"Six Seals": "六重封印",
	"Clear all six challenge contracts.": "完成全部六个挑战契约。",
	"Relic Keeper": "遗物保管者",
	"Discover all twelve relics.": "发现全部十二件遗物。",
	"Complete Marginalia": "完整页边集",
	"Discover all thirty-six techniques.": "发现全部三十六种技巧。",
	"Restored Codex": "修复图鉴",
	"Defeat every enemy archetype.": "击败所有敌人原型。",
	"Redline Reader": "红线读者",
	"Finish a Redline Draft.": "完成一次红线草稿。",
	"Living Memory": "活体记忆",
	"Recover 250 Memory across all drafts.": "在所有草稿中累计回收 250 点记忆。",
	"Map the Margins": "绘制页边",
	"Discover all nine routes through the Archive.": "发现档案馆中的全部九条路线。",
	"Order in the Margins": "页边秩序",
	"Complete your first Page Directive.": "完成第一个页章指令。",
	"Field Editor": "战地编辑",
	"Complete twenty Page Directives.": "完成二十个页章指令。",
	"Today's Reader": "今日读者",
	"Clear a Daily Chronicle.": "通关一次每日编年史。",
	"Serial Reader": "连载读者",
	"Build a seven-day Daily Chronicle streak.": "达成七天每日编年史连胜。",
	"HEARTBIND": "心之装订",
	"+1 MAX HEALTH / RANK": "每级 +1 最大生命",
	"MASTER: START WITH WARD +2": "精通：开局获得 +2 护盾",
	"HONED NIB": "锐化笔尖",
	"+0.2 BLADE DAMAGE / RANK": "每级 +0.2 斩击伤害",
	"MASTER: +10% BOSS DAMAGE": "精通：对首领伤害 +10%",
	"+5% LUCK / RANK": "每级 +5% 幸运",
	"MASTER: +10% INK VALUE": "精通：墨迹价值 +10%",
	"QUICK MARGIN": "疾速页边",
	"+3 MOVE SPEED / RANK": "每级 +3 移动速度",
	"MASTER: 10% FASTER DASH": "精通：冲刺加快 10%",
	"DEEP INKWELL": "深邃墨池",
	"4% FASTER INK ART / RANK": "每级使墨术冷却加快 4%",
	"MASTER: +15% ART DAMAGE": "精通：墨术伤害 +15%",
	"READER'S THREAD": "读者之线",
	"+18 PICKUP REACH / RANK": "每级 +18 拾取范围",
	"MASTER: +45 EXTRA REACH": "精通：额外 +45 拾取范围",
	"Available from the first page.": "从第一页起即可使用。",
	"Complete one draft, win or lose.": "完成一局草稿，无论胜负。",
	"Defeat 25 masks across all drafts.": "在所有草稿中累计击败 25 个面具。",
	"Reach Page 8.": "抵达第 8 页。",
	"Clear three different contracts.": "完成三个不同契约。",

	# Contracts and Proof depth.
	"OPEN DRAFT": "开放草稿",
	"The intended balance. No special clauses.": "标准平衡，无特殊条款。",
	"QUICK EDITION": "速刊版",
	"Pages turn every 32 seconds and enemies move faster. ×1.40 score.": "每 32 秒翻页，敌人移动更快。得分 ×1.40。",
	"LIVING MARGINS": "活页边",
	"Larger, faster hordes with lighter bodies. ×1.35 score.": "敌群更大更快，但生命更低。得分 ×1.35。",
	"SEALED ARCHIVE": "封闭档案馆",
	"Recovery drops are sealed; enemies endure longer. ×1.45 score.": "不掉落恢复品，敌人更耐久。得分 ×1.45。",
	"GLASS SCRIPT": "玻璃文稿",
	"+35% blade damage, fragile body, deadlier masks. ×1.50 score.": "+35% 斩击伤害，自身更脆弱，面具更致命。得分 ×1.50。",
	"CURSED INK": "诅咒墨水",
	"Far more elite affixes; every victory pays Memory. ×1.55 score.": "精英词缀大幅增多；每次胜利奖励记忆。得分 ×1.55。",
	"STORY DRAFT": "故事草稿",
	"STANDARD DRAFT": "标准草稿",
	"REDLINE DRAFT": "红线草稿",
	"STORY": "故事",
	"STANDARD": "标准",
	"REDLINE": "红线",
	"LIVING MARGIN": "活页边",
	"OPEN PROOF": "开放校样",
	"The restored baseline. No cumulative proof clauses.": "修复后的基准难度，无叠加校样条款。",
	"BLOOD INK": "血墨",
	"Masks deal 4% more damage.": "面具造成的伤害提高 4%。",
	"HEAVY STOCK": "厚重纸材",
	"Masks have 6% more health.": "面具生命提高 6%。",
	"CROWDED MARGINS": "拥挤页边",
	"Hordes arrive 6% faster and hold 8% more masks.": "敌群出现速度提高 6%，上限提高 8%。",
	"MARKED COPIES": "标记副本",
	"Elite affixes appear 8% more often.": "精英词缀出现率提高 8%。",
	"SEALED REMEDIES": "封存药品",
	"Recovery drops are 15% scarcer.": "恢复品掉率降低 15%。",
	"RUNNING TYPE": "疾行字体",
	"Masks move 6% faster.": "面具移动速度提高 6%。",
	"THE RED PEN": "赤红之笔",
	"Bosses carry 12% more health.": "首领生命提高 12%。",
	"BROKEN GUTTER": "破损页沟",
	"Nara's dash recovers 10% slower.": "奈良的冲刺冷却变慢 10%。",
	"LAST DEADLINE": "最终截稿期",
	"Pages turn 8% sooner.": "翻页时间缩短 8%。",
	"AUTHOR'S PROOF": "作者校样",
	"Masks gain 6% health and 4% damage; bosses gain another 8% health.": "面具生命 +6%、伤害 +4%；首领额外获得 8% 生命。",

	# Events and Page Directives.
	"THE FORGOTTEN SHRINE": "遗忘神龛",
	"Names scratched into the stone answer when Nara touches the blade.": "奈良触碰刀刃时，刻在石上的姓名作出了回应。",
	"OFFER A HEARTBEAT": "献出一次心跳",
	"Lose 1 max health; gain a relic.": "失去 1 最大生命；获得一件遗物。",
	"READ EVERY NAME": "读出每个名字",
	"Recover 5 Memory shards.": "获得 5 点记忆。",
	"REST IN THE MARGIN": "在页边休息",
	"Recover 3 health.": "恢复 3 生命。",
	"THE BLEEDING INDEX": "泣血索引",
	"A catalogue points toward books the Editors were ordered to destroy.": "目录指向编辑者奉命销毁的书籍。",
	"FOLLOW THE RED LINE": "沿着红线",
	"Gain a random technique.": "获得一种随机技巧。",
	"CUT OUT THE ENTRY": "剪去条目",
	"+0.5 damage; lose 1 max health.": "+0.5 伤害；失去 1 最大生命。",
	"SEAL THE DRAWER": "封住抽屉",
	"Gain 3 guard for the next battle.": "下一场战斗获得 3 点护盾。",
	"THE MASKLESS CHILD": "无面具之子",
	"A recovered memory asks whether being forgotten still counts as being alive.": "一段恢复的记忆问：被遗忘是否还算活着。",
	"PROMISE TO RETURN": "许诺归来",
	"+1 max health and heal.": "+1 最大生命并恢复生命。",
	"SHARE IORI'S RIBBON": "分享伊织的缎带",
	"+6% critical chance.": "+6% 暴击率。",
	"LEAVE A MAP": "留下一张地图",
	"+8 movement speed.": "+8 移动速度。",
	"CONTRABAND TEAHOUSE": "违禁茶馆",
	"Morrow remembers a room where banned stories were once traded over black tea.": "莫罗想起一间曾以红茶交换禁忌故事的房间。",
	"DRINK THE LAST CUP": "饮下最后一杯",
	"Fully heal and gain 2 guard.": "完全恢复并获得 2 点护盾。",
	"TRADE A TRUE STORY": "交换真实故事",
	"Gain a relic; lose 2 health.": "获得一件遗物；失去 2 生命。",
	"SEARCH THE CELLAR": "搜查地窖",
	"Ambush by 3 elites; gain 5 Memory now.": "遭遇 3 名精英伏击；立即获得 5 点记忆。",
	"THE UNBOUND FOOTNOTE": "未装订的脚注",
	"A sentence crawls free of its page and begs Nara to choose its ending.": "一句话爬出书页，恳求奈良替它选择结局。",
	"MAKE IT A WEAPON": "把它写成武器",
	"+0.4 damage.": "+0.4 伤害。",
	"MAKE IT A SHELTER": "把它写成庇护所",
	"+2 max health.": "+2 最大生命。",
	"LET IT STAY UNFINISHED": "让它保持未完成",
	"+15% luck this run.": "本局幸运 +15%。",
	"THE RED MARKET": "赤红市集",
	"Masked merchants sell memories whose owners have not forgotten losing them.": "戴面具的商贩出售记忆，而它们的主人仍记得失去时的痛苦。",
	"BUY THE SEALED BOX": "购买密封盒",
	"Gain a random relic.": "获得一件随机遗物。",
	"STEAL BACK THE NAMES": "夺回姓名",
	"Fight 4 elites; gain 8 Memory now.": "迎战 4 名精英；立即获得 8 点记忆。",
	"BURN THE LEDGER": "焚毁账簿",
	"+10% attack speed.": "+10% 攻击速度。",
	"THE AUTHOR'S SHADOW": "作者之影",
	"Morrow's discarded shadow still knows how to improve a killing sentence.": "莫罗抛弃的影子仍知道如何润色一句杀人之语。",
	"ACCEPT THE REVISION": "接受修订",
	"Gain a random technique and 2 guard.": "获得一种随机技巧与 2 点护盾。",
	"REJECT PERFECTION": "拒绝完美",
	"ASK ABOUT IORI": "询问伊织",
	"Recover 9 Memory shards.": "获得 9 点记忆。",
	"THE WHITE ROOM": "纯白之室",
	"Nothing has ever been written here. Even wounds briefly forget their names.": "这里从未写下任何东西，连伤口也会短暂忘记自己的名字。",
	"WRITE YOUR SCARS": "写下伤痕",
	"Fully heal; +1 max health.": "完全恢复；+1 最大生命。",
	"WRITE YOUR ANGER": "写下愤怒",
	"+0.75 damage; lose 2 health.": "+0.75 伤害；失去 2 生命。",
	"LEAVE IT BLANK": "保持空白",
	"Gain 5 guard.": "获得 5 点护盾。",
	"THE LAST READER": "最后的读者",
	"An old reader has waited decades to learn whether the world survives its ending.": "一位老读者等了数十年，只想知道世界能否熬过自己的结局。",
	"TELL THE TRUTH": "说出真相",
	"+20% critical damage.": "+20% 暴击伤害。",
	"TELL A KIND LIE": "说一个善意谎言",
	"Recover 4 health and 4 Memory.": "恢复 4 生命并获得 4 点记忆。",
	"HAND OVER THE BLADE": "交出刀刃",
	"Gain a relic; summon 2 elites.": "获得一件遗物；召唤 2 名精英。",
	"REDACTION QUOTA": "删改配额",
	"Cut down ten masks before the page turns.": "翻页前击败十个面具。",
	"MEMORY +2": "记忆 +2",
	"GATHER LOOSE INK": "收集散墨",
	"Recover ten scattered Ink marks.": "收集十枚散落墨迹。",
	"WARD +3": "护盾 +3",
	"HOLD THE WHISPER": "守住低语",
	"Stand inside the speaking margin for seven seconds.": "在低语页边内停留七秒。",
	"RECOVER +2": "恢复 +2",
	"FINISH THE SENTENCE": "完成语句",
	"Defeat fourteen Bindery masks.": "击败十四个装订所面具。",
	"MEMORY +3": "记忆 +3",
	"BREAK THE CENSOR CELL": "击破审查牢笼",
	"Defeat two marked elite masks.": "击败两个被标记的精英面具。",
	"FREE TECHNIQUE": "免费技巧",
	"READ AGAINST THE BINDING": "逆着装订阅读",
	"Hold the forbidden circle for nine seconds.": "守住禁忌圆环九秒。",
	"WARD +4": "护盾 +4",
	"BEAT THE PRESS": "抢在印刷机之前",
	"Defeat eighteen masks before the verdict lands.": "判决落下前击败十八个面具。",
	"INK ART RESTORED": "墨术已恢复",
	"REJECT THE FINAL PROOF": "驳回最终校样",
	"Defeat three elite proofreaders.": "击败三个精英校对者。",
	"RELIC RESTORED": "遗物已修复",
	"RECOVER TESTIMONY": "回收证词",
	"Gather sixteen living Ink marks.": "收集十六枚活体墨迹。",
	"RECOVER +3 · MEMORY +3": "恢复 +3 · 记忆 +3",
	"THE COMMA RUSH": "逗号突袭",
	"SCRIPTORIUM FIRING LINE": "缮写室火力线",
	"BLACK INDEX CELL": "黑色索引小队",
	"THE BOUND SENTENCE": "装订之句",
	"NAME-THIEF CABAL": "窃名者密会",
	"IRON CENSOR ESCORT": "铁甲审查护卫",
	"THE RED PRESS GUARD": "赤红印刷守卫",
	"FALSE CATALOGUE": "伪目录",
	"THE FINAL MARGINS": "最终页边",

	# Remaining shell, HUD and system notices.
	"BUILD": "版本",
	"INKBOUND": "墨缚",
	"BLADE OF THE BLANK PAGE": "空白之页的刀刃",
	"SURVIVE. CUT. REWRITE.": "生存。斩断。重写。",
	"FIND IORI BEYOND THE REDACTIONS": "穿过删改，寻找伊织",
	"NEW GAME": "新游戏",
	"CONTINUE / LOAD": "继续 / 读取",
	"CONTINUE / LOAD\nNO SAVED DRAFT": "继续 / 读取\n没有已保存的草稿",
	"NEW GAME WILL REPLACE THE SAVED DRAFT": "新游戏将覆盖已保存的草稿",
	"PRESS AGAIN\nERASE DRAFT": "再次按下\n覆盖草稿",
	"CHOOSE A STARTING BLADE": "选择初始刀刃",
	"STARTING BLADE STILL LOCKED": "初始刀刃尚未解锁",
	"ARCHIVE CODEX": "档案馆图鉴",
	"RESTORED ACHIEVEMENTS": "已修复成就",
	"RECENT DRAFTS": "近期草稿",
	"STORY ARCHIVE": "故事档案",
	"RESTORATION BOARD": "修复面板",
	"RESTORE THE ARCHIVE  ·  PERMANENT MEMORIES": "修复档案馆  ·  永久记忆",
	"THE PROOF LEDGER": "校样账簿",
	"DAILY CHRONICLE": "每日编年史",
	"ONE DATE · ONE SEED · ONE SHARED DRAFT": "同一日期 · 同一种子 · 同一份草稿",
	"STANDARD · MARGINALIA · PROOF 0": "标准难度 · 页边之刃 · 校样 0",
	"THE PAGE GOES BLACK": "书页归于黑暗",
	"THE PAGE REMEMBERS": "书页仍记得",
	"REWRITE THE PAGE": "重写此页",
	"BEGIN ANOTHER DRAFT": "开始另一份草稿",
	"NEXT DRAFT AWAITS": "下一份草稿正在等待",
	"DRAFT LOST": "草稿失败",
	"DAILY DRAFT LOST": "每日草稿失败",
	"CHOOSE THE NEXT STROKE": "选择下一笔",
	"RESTORE ONE RELIC": "修复一件遗物",
	"FOUND IN THE MARGIN": "在页边发现",
	"A MEMORY IN THE MARGIN": "页边的一段记忆",
	"PAGE DIRECTIVE": "页章指令",
	"DIRECTIVE COMPLETE": "指令完成",
	"DIRECTIVE EXPIRED": "指令已过期",
	"PAGE DIRECTIVE REWARD": "页章指令奖励",
	"ENCOUNTER SQUAD": "遭遇小队",
	"CHOOSE THE NEXT MARGIN": "选择下一条页边路线",
	"MARGIN CHOSEN": "页边路线已选定",
	"ARCHIVE CACHE · CHOOSE ONE RELIC": "档案秘藏 · 选择一件遗物",
	"MEMORY BARGAIN · CHOOSE ONE RELIC": "记忆交易 · 选择一件遗物",
	"STOLEN RELIC · CHOOSE BEFORE THE AMBUSH": "被盗遗物 · 伏击前完成选择",
	"RELIC ARCHIVE COMPLETE · MEMORY +5": "遗物档案已完成 · 记忆 +5",
	"SAVED DRAFT RECOVERED FROM BACKUP": "已从备份恢复保存的草稿",
	"DAMAGED DRAFT PRESERVED  ·  START A NEW GAME": "损坏草稿已保留  ·  请开始新游戏",
	"ARCHIVE RECOVERED FROM BACKUP": "已从备份恢复档案",
	"ARCHIVE REQUIRES A NEWER GAME VERSION": "此档案需要更新版本的游戏",
	"DAMAGED ARCHIVE PRESERVED  ·  NEW PROFILE": "损坏档案已保留  ·  已创建新档案",
	"SAVE FAILED  ·  DRAFT STILL RUNNING": "保存失败  ·  草稿仍在运行",
	"SAVED DRAFT COULD NOT BE LOADED": "无法读取保存的草稿",
	"GAMEPAD DISCONNECTED": "手柄已断开",
	"FOCUS RESTORED  ·  PRESS PAUSE TO CONTINUE": "窗口焦点已恢复  ·  按暂停键继续",
	"MEMORY STILL LOCKED": "记忆尚未解锁",
	"THAT ENDING HAS NOT BEEN RESTORED": "该结局尚未修复",
	"NO DRAFTS RECORDED": "尚无草稿记录",
	"NO DRAFTS RECORDED\n\nCOMPLETE A RUN TO BEGIN THE ARCHIVE LEDGER.": "尚无草稿记录\n\n完成一局后即可开始记录档案账簿。",
	"NO SPECIAL CLAUSES": "无特殊条款",
	"OPEN PROOF · NO CUMULATIVE CLAUSES": "开放校样 · 无叠加条款",
	"FIELD MANUAL": "战地手册",
	"F1 / H  FIELD MANUAL": "F1 / H  战地手册",
	"F1 / LT  FIELD MANUAL": "F1 / LT  战地手册",
	"F1 / H  MANUAL": "F1 / H  手册",
	"LT  MANUAL": "LT  手册",
	"LT/F1  MANUAL": "LT/F1  手册",
	"O / F10  OPTIONS": "O / F10  选项",
	"O / VIEW  OPTIONS": "O / VIEW  选项",
	"VIEW  OPTIONS": "VIEW  选项",
	"D-PAD DOWN": "十字键下",
	"D-PAD UP": "十字键上",
	"D-PAD LEFT": "十字键左",
	"D-PAD RIGHT": "十字键右",
	"LEFT SHOULDER": "左肩键",
	"RIGHT SHOULDER": "右肩键",
	"LEFT STICK": "左摇杆",
	"RIGHT STICK": "右摇杆",
	"ACHIEVEMENT RESTORED": "成就已修复",
	"DEFAULT BINDINGS RESTORED": "默认按键已恢复",
	"REBIND CANCELLED  ·  A/ENTER TO TRY AGAIN": "重新绑定已取消  ·  按 A/回车重试",
	"CLEARED": "已通关",
	"LOST": "失败",
	"WIN": "胜利",
	"DAILY": "每日",
	"TODAY": "今日",
	"MEMORY": "记忆",
	"READY": "就绪",
	"WARD +5": "护盾 +5",
	"RED EDITOR · PAGE 4": "赤红编辑 · 第 4 页",
	"FORBIDDEN BINDER · PAGE 8": "禁忌装订者 · 第 8 页",
	"FIRST AUTHOR · PAGE 12": "初代作者 · 第 12 页",
	"Y/△  CODEX": "Y/△  图鉴",
	"B/○  ACHIEVEMENTS": "B/○  成就",
	"X/□  HISTORY": "X/□  记录",
	"RT  STORY": "RT  故事",
	"1 / X  SAVE & RETURN": "1 / X  保存并返回",
	"Y/△ OR ESC  CLOSE": "Y/△ 或 ESC  关闭",
	"B/○ OR ESC  CLOSE": "B/○ 或 ESC  关闭",
	"X/□ OR ESC  CLOSE": "X/□ 或 ESC  关闭",
	"RT OR ESC  CLOSE": "RT 或 ESC  关闭",
	"T / DOWN  DAILY CHRONICLE": "T / 下  每日编年史",
	"M / RS  OPEN RESTORATION BOARD": "M / 右摇杆  打开修复面板",
	"T / DOWN  OPEN OR CLOSE  ·  B / ESC  BACK": "T / 下  打开或关闭  ·  B / ESC  返回",
	"D-PAD / ARROWS  SELECT  ·  A / ENTER  USE  ·  B / ESC  CLOSE": "方向键选择  ·  A / 回车 使用  ·  B / ESC  关闭",
	"D-PAD / ARROWS  SELECT  ·  A / ENTER  RESTORE  ·  B / ESC  CLOSE": "方向键选择  ·  A / 回车 修复  ·  B / ESC  关闭",
	"X / Y / B  OR  1 / 2 / 3  ·  CHOICE IS PERMANENT FOR THIS DRAFT": "X / Y / B 或 1 / 2 / 3  ·  选择在本局草稿中永久生效",
	"MENDED": "修补",
	"MEND+": "修补+",
	"MERCY +1": "仁慈 +1",
	"PARRY?": "招架？",
	"REDACT": "删改",
	"BIND": "束缚",
	"CACHE": "秘藏",
	"CONTRABAND BURNS": "违禁品焚毁",
	"CONTRABAND CLAIMED · WARD +1": "已夺取违禁品 · 护盾 +1",
	"WHISPER ANSWERS · WARD +1": "低语回应 · 护盾 +1",
	"WHITE REVISION · RECOVER +2": "纯白修订 · 恢复 +2",
	"FIELD RELIC · CHOOSE ONE MEMORY": "战地遗物 · 选择一段记忆",
	"PANEL PAUSED\nESC TO CONTINUE": "战场已暂停\n按 ESC 继续",
	"WASD MOVE  ·  MOUSE/J SLASH  ·  SPACE/K DASH  ·  E ART  ·  ESC PAUSE": "WASD 移动  ·  鼠标/J 斩击  ·  空格/K 冲刺  ·  E 墨术  ·  ESC 暂停",
	"RELICS —": "遗物 —",
	"↑↓ SELECT  ·  A/ENTER PLAY  ·  RT/ESC CLOSE": "↑↓ 选择  ·  A/回车 播放  ·  RT/ESC 关闭",
	"Reach Page 4 and confront the Red Editor": "抵达第 4 页并迎战赤红编辑",
	"DIRECTIVE COMPLETE!": "指令完成！",
	"MISPRINT!": "错印！",
	"RECOVERY DROP!": "恢复品掉落！",
	"AOE: INK BOMB!": "范围道具：墨爆弹！",
	"REDACTED!": "已删改！",
	"ALL MARGINS CALL!": "页边尽数归来！",
	"RED FRENZY!": "赤红狂热！",
	"TIME REDACTED!": "时间已删改！",
	"ECHO!": "回响！",
	"INK+": "墨迹+",
	"THE END?": "终章？",
	"PERIOD!": "句点！",
	"ZIP!": "咻！",
	"ERRATA...": "勘误……",
	"BEHIND YOU!": "身后！",
	"SCRIBE!": "缮写！",
	"SEAL!": "封印！",
	"SPILL!": "泼墨！",
	"BIND!": "装订！",
	"REVISE!": "修订！",
	"EDIT!": "编辑！",
	"APPEND!": "追加！",
	"CRIT!": "暴击！",
	"KRAK!": "咔嚓！",
	"PARRY!": "格挡！",
	"SHIELD BROKEN!": "护盾破碎！",
	"CENSORED!": "已审查！",
	"SPLAT!": "啪！",
	"BOOM!": "轰！",
}

static var _registered := false
static var _ui_theme: Theme


static func register_translations() -> void:
	if _registered:
		return
	var translation := Translation.new()
	translation.locale = LANGUAGE_CHINESE
	for source in ZH_CN:
		translation.add_message(StringName(source), StringName(ZH_CN[source]))
	TranslationServer.add_translation(translation)
	_registered = true


static func effective_locale(language_setting: String) -> String:
	if language_setting == LANGUAGE_CHINESE:
		return LANGUAGE_CHINESE
	if language_setting == LANGUAGE_ENGLISH:
		return LANGUAGE_ENGLISH
	return LANGUAGE_CHINESE if OS.get_locale_language().to_lower() == "zh" else LANGUAGE_ENGLISH


static func apply_language(language_setting: String) -> String:
	register_translations()
	var locale := effective_locale(language_setting)
	TranslationServer.set_locale(locale)
	return locale


static func text(source: Variant) -> String:
	return TranslationServer.translate(str(source))


static func gameplay_text(source: Variant) -> String:
	var source_text := str(source)
	var translated := text(source_text)
	if translated != source_text or not TranslationServer.get_locale().begins_with("zh"):
		return translated
	if source_text.begins_with("PAGE ") and source_text.trim_prefix("PAGE ").is_valid_int():
		return "第 %s 页" % source_text.trim_prefix("PAGE ")
	if source_text.begins_with("MEMORY +"):
		return "记忆 +%s" % source_text.trim_prefix("MEMORY +")
	if source_text.begins_with("INK BOMB!  "):
		return "墨爆弹！  %s" % source_text.trim_prefix("INK BOMB!  ")
	if source_text.begins_with("RESTORE ") and source_text.ends_with("!"):
		return "修复 %s！" % source_text.trim_prefix("RESTORE ").trim_suffix("!")
	var hit_marker := source_text.rfind("!  ")
	if hit_marker > 0:
		var title := source_text.left(hit_marker)
		var localized_title := text(title)
		if localized_title != title:
			return "%s！  %s" % [localized_title, source_text.substr(hit_marker + 3)]
	return source_text


static func format(source: String, values: Array) -> String:
	return text(source) % values


static func localized(value: Variant) -> Variant:
	if value is String or value is StringName:
		return text(value)
	if value is Dictionary:
		var result := {}
		for key in value:
			result[key] = localized(value[key])
		return result
	if value is Array:
		var result: Array = []
		for entry in value:
			result.append(localized(entry))
		return result
	return value


static func language_display_name(language_setting: String) -> String:
	match language_setting:
		LANGUAGE_ENGLISH:
			return text("ENGLISH")
		LANGUAGE_CHINESE:
			return text("SIMPLIFIED CHINESE")
	return text("SYSTEM")


static func ui_theme() -> Theme:
	if _ui_theme != null:
		return _ui_theme
	var font := SystemFont.new()
	font.font_names = PackedStringArray([
		"Microsoft YaHei UI",
		"Microsoft YaHei",
		"Noto Sans CJK SC",
		"Source Han Sans SC",
		"Droid Sans Fallback",
		"Arial Unicode MS",
		"Arial",
	])
	font.font_weight = 500
	_ui_theme = Theme.new()
	_ui_theme.default_font = font
	return _ui_theme
